apiVersion: v1
kind: Pod 
metadata: 
  name: my-pod
  labels:
    app: myapp
  namespace: dev 
spec: 
  containers:
    - name: my-container
      image: nginx:1.29
      ports:
        - containerPort: 80  
  resources: 
    requests:
      memory: 64Mi
      cpu: 250m
    limits: 
      memory: 128Mi
      cpu: 300m        
